// This file was auto-generated by 'typesafe-i18n'. Any manual changes will be overwritten.
/* eslint-disable */
import type { BaseTranslation as BaseTranslationType, LocalizedString } from 'typesafe-i18n'

export type BaseTranslation = BaseTranslationType
export type BaseLocale = 'zh'

export type Locales =
	| 'en'
	| 'zh'

export type Translation = RootTranslation

export type Translations = RootTranslation

type RootTranslation = {
	/**
	 * 播​放​白​噪​音
	 */
	play: string
	/**
	 * 暂​停​白​噪​音
	 */
	pause: string
	/**
	 * 停​止​白​噪​音
	 */
	stop: string
	/**
	 * 随​机​播​放​白​噪​音
	 */
	playRandom: string
	/**
	 * 打​开​白​噪​音​配​置
	 */
	openConfig: string
	timerOptions: {
		/**
		 * 5​分​钟
		 */
		'5': string
		/**
		 * 1​0​分​钟
		 */
		'10': string
		/**
		 * 1​5​分​钟
		 */
		'15': string
		/**
		 * 2​0​分​钟
		 */
		'20': string
		/**
		 * 2​5​分​钟
		 */
		'25': string
		/**
		 * 3​0​分​钟
		 */
		'30': string
		/**
		 * 4​5​分​钟
		 */
		'45': string
		/**
		 * 1​小​时
		 */
		'60': string
		/**
		 * 1​.​5​小​时
		 */
		'90': string
		/**
		 * 2​小​时
		 */
		'120': string
	}
	/**
	 * 白​噪​音​设​置
	 */
	config: string
	/**
	 * [​暂​停​]​ 
	 */
	paused: string
	/**
	 * [​时​间​到​]​ 
	 */
	stopped: string
	/**
	 * 白​噪​音​未​播​放
	 */
	notPlaying: string
	/**
	 * 白​噪​音​列​表
	 */
	list: string
	/**
	 * 启​用​定​时​器
	 */
	enableTimer: string
	/**
	 * 可​用​作​简​易​番​茄​钟
	 */
	enableTimerDescription: string
	/**
	 * 继​续
	 */
	resumeTimer: string
	/**
	 * 暂​停
	 */
	pauseTimer: string
	/**
	 * 计​时​结​束
	 */
	timerEnd: string
	/**
	 * 重​置​计​时​器
	 */
	resetTimer: string
	/**
	 * 设​定​时​间
	 */
	selectTimer: string
	/**
	 * 计​时​结​束​时​停​止​白​噪​音
	 */
	timerEndAction: string
	/**
	 * 计​时​结​束​时​播​放​提​示​音
	 */
	timerNotify: string
	sounds: {
		/**
		 * 鸟​叫
		 */
		birds: string
		/**
		 * 蟋​蟀
		 */
		crickets: string
		/**
		 * 乌​鸦
		 */
		crows: string
		/**
		 * 狗​吠
		 */
		dogBarking: string
		/**
		 * 马​蹄​声
		 */
		horseGalopp: string
		/**
		 * 猫​头​鹰
		 */
		owl: string
		/**
		 * 海​鸥
		 */
		seagulls: string
		/**
		 * 鲸​鱼
		 */
		whale: string
		/**
		 * 篝​火
		 */
		campfire: string
		/**
		 * 水​滴
		 */
		droplets: string
		/**
		 * 呼​啸​的​风
		 */
		howlingWind: string
		/**
		 * 河​流
		 */
		river: string
		/**
		 * 雪​地​行​走
		 */
		walkInSnow: string
		/**
		 * 落​叶​行​走
		 */
		walkOnLeaves: string
		/**
		 * 瀑​布
		 */
		waterfall: string
		/**
		 * 海​浪
		 */
		waves: string
		/**
		 * 棕​噪​音
		 */
		brownNoise: string
		/**
		 * 粉​噪​音
		 */
		pinkNoise: string
		/**
		 * 白​噪​音
		 */
		whiteNoise: string
		/**
		 * 咖​啡​馆
		 */
		cafe: string
		/**
		 * 教​堂
		 */
		church: string
		/**
		 * 建​筑​工​地
		 */
		constructionSite: string
		/**
		 * 拥​挤​的​酒​吧
		 */
		crowdedBar: string
		/**
		 * 实​验​室
		 */
		laboratory: string
		/**
		 * 洗​衣​房
		 */
		laundryRoom: string
		/**
		 * 夜​晚​的​村​庄
		 */
		nightVillage: string
		/**
		 * 办​公​室
		 */
		office: string
		/**
		 * 地​铁​站
		 */
		subwayStation: string
		/**
		 * 超​市
		 */
		supermarket: string
		/**
		 * 水​下
		 */
		underwater: string
		/**
		 * 大​雨
		 */
		heavyRain: string
		/**
		 * 小​雨
		 */
		lightRain: string
		/**
		 * 雨​打​叶
		 */
		rainOnLeaves: string
		/**
		 * 雨​打​伞
		 */
		rainOnUmbrella: string
		/**
		 * 雨​打​窗
		 */
		rainOnWindow: string
		/**
		 * 沸​水
		 */
		boilingWater: string
		/**
		 * 气​泡
		 */
		bubbles: string
		/**
		 * 吊​扇
		 */
		ceilingFan: string
		/**
		 * 时​钟
		 */
		clock: string
		/**
		 * 烘​干​机
		 */
		dryer: string
		/**
		 * 键​盘
		 */
		keyboard: string
		/**
		 * 纸​张
		 */
		paper: string
		/**
		 * 打​字​机
		 */
		typewriter: string
		/**
		 * 洗​衣​机
		 */
		washingMachine: string
		/**
		 * 风​铃
		 */
		windChimes: string
		/**
		 * 人​群
		 */
		crowd: string
		/**
		 * 烟​花
		 */
		fireworks: string
		/**
		 * 高​速​公​路
		 */
		highway: string
		/**
		 * 道​路
		 */
		road: string
		/**
		 * 交​通
		 */
		traffic: string
	}
	categories: {
		/**
		 * 动​物
		 */
		animals: string
		/**
		 * 自​然​环​境
		 */
		nature: string
		/**
		 * 基​础​噪​音
		 */
		noise: string
		/**
		 * 场​所​环​境
		 */
		places: string
		/**
		 * 雨​声
		 */
		rain: string
		/**
		 * 物​品​声​音
		 */
		things: string
		/**
		 * 交​通​工​具
		 */
		transport: string
		/**
		 * 城​市​声​音
		 */
		urban: string
		/**
		 * 合​成​噪​音
		 */
		synthetic: string
	}
}

export type TranslationFunctions = {
	/**
	 * 播放白噪音
	 */
	play: () => LocalizedString
	/**
	 * 暂停白噪音
	 */
	pause: () => LocalizedString
	/**
	 * 停止白噪音
	 */
	stop: () => LocalizedString
	/**
	 * 随机播放白噪音
	 */
	playRandom: () => LocalizedString
	/**
	 * 打开白噪音配置
	 */
	openConfig: () => LocalizedString
	timerOptions: {
		/**
		 * 5分钟
		 */
		'5': () => LocalizedString
		/**
		 * 10分钟
		 */
		'10': () => LocalizedString
		/**
		 * 15分钟
		 */
		'15': () => LocalizedString
		/**
		 * 20分钟
		 */
		'20': () => LocalizedString
		/**
		 * 25分钟
		 */
		'25': () => LocalizedString
		/**
		 * 30分钟
		 */
		'30': () => LocalizedString
		/**
		 * 45分钟
		 */
		'45': () => LocalizedString
		/**
		 * 1小时
		 */
		'60': () => LocalizedString
		/**
		 * 1.5小时
		 */
		'90': () => LocalizedString
		/**
		 * 2小时
		 */
		'120': () => LocalizedString
	}
	/**
	 * 白噪音设置
	 */
	config: () => LocalizedString
	/**
	 * [暂停] 
	 */
	paused: () => LocalizedString
	/**
	 * [时间到] 
	 */
	stopped: () => LocalizedString
	/**
	 * 白噪音未播放
	 */
	notPlaying: () => LocalizedString
	/**
	 * 白噪音列表
	 */
	list: () => LocalizedString
	/**
	 * 启用定时器
	 */
	enableTimer: () => LocalizedString
	/**
	 * 可用作简易番茄钟
	 */
	enableTimerDescription: () => LocalizedString
	/**
	 * 继续
	 */
	resumeTimer: () => LocalizedString
	/**
	 * 暂停
	 */
	pauseTimer: () => LocalizedString
	/**
	 * 计时结束
	 */
	timerEnd: () => LocalizedString
	/**
	 * 重置计时器
	 */
	resetTimer: () => LocalizedString
	/**
	 * 设定时间
	 */
	selectTimer: () => LocalizedString
	/**
	 * 计时结束时停止白噪音
	 */
	timerEndAction: () => LocalizedString
	/**
	 * 计时结束时播放提示音
	 */
	timerNotify: () => LocalizedString
	sounds: {
		/**
		 * 鸟叫
		 */
		birds: () => LocalizedString
		/**
		 * 蟋蟀
		 */
		crickets: () => LocalizedString
		/**
		 * 乌鸦
		 */
		crows: () => LocalizedString
		/**
		 * 狗吠
		 */
		dogBarking: () => LocalizedString
		/**
		 * 马蹄声
		 */
		horseGalopp: () => LocalizedString
		/**
		 * 猫头鹰
		 */
		owl: () => LocalizedString
		/**
		 * 海鸥
		 */
		seagulls: () => LocalizedString
		/**
		 * 鲸鱼
		 */
		whale: () => LocalizedString
		/**
		 * 篝火
		 */
		campfire: () => LocalizedString
		/**
		 * 水滴
		 */
		droplets: () => LocalizedString
		/**
		 * 呼啸的风
		 */
		howlingWind: () => LocalizedString
		/**
		 * 河流
		 */
		river: () => LocalizedString
		/**
		 * 雪地行走
		 */
		walkInSnow: () => LocalizedString
		/**
		 * 落叶行走
		 */
		walkOnLeaves: () => LocalizedString
		/**
		 * 瀑布
		 */
		waterfall: () => LocalizedString
		/**
		 * 海浪
		 */
		waves: () => LocalizedString
		/**
		 * 棕噪音
		 */
		brownNoise: () => LocalizedString
		/**
		 * 粉噪音
		 */
		pinkNoise: () => LocalizedString
		/**
		 * 白噪音
		 */
		whiteNoise: () => LocalizedString
		/**
		 * 咖啡馆
		 */
		cafe: () => LocalizedString
		/**
		 * 教堂
		 */
		church: () => LocalizedString
		/**
		 * 建筑工地
		 */
		constructionSite: () => LocalizedString
		/**
		 * 拥挤的酒吧
		 */
		crowdedBar: () => LocalizedString
		/**
		 * 实验室
		 */
		laboratory: () => LocalizedString
		/**
		 * 洗衣房
		 */
		laundryRoom: () => LocalizedString
		/**
		 * 夜晚的村庄
		 */
		nightVillage: () => LocalizedString
		/**
		 * 办公室
		 */
		office: () => LocalizedString
		/**
		 * 地铁站
		 */
		subwayStation: () => LocalizedString
		/**
		 * 超市
		 */
		supermarket: () => LocalizedString
		/**
		 * 水下
		 */
		underwater: () => LocalizedString
		/**
		 * 大雨
		 */
		heavyRain: () => LocalizedString
		/**
		 * 小雨
		 */
		lightRain: () => LocalizedString
		/**
		 * 雨打叶
		 */
		rainOnLeaves: () => LocalizedString
		/**
		 * 雨打伞
		 */
		rainOnUmbrella: () => LocalizedString
		/**
		 * 雨打窗
		 */
		rainOnWindow: () => LocalizedString
		/**
		 * 沸水
		 */
		boilingWater: () => LocalizedString
		/**
		 * 气泡
		 */
		bubbles: () => LocalizedString
		/**
		 * 吊扇
		 */
		ceilingFan: () => LocalizedString
		/**
		 * 时钟
		 */
		clock: () => LocalizedString
		/**
		 * 烘干机
		 */
		dryer: () => LocalizedString
		/**
		 * 键盘
		 */
		keyboard: () => LocalizedString
		/**
		 * 纸张
		 */
		paper: () => LocalizedString
		/**
		 * 打字机
		 */
		typewriter: () => LocalizedString
		/**
		 * 洗衣机
		 */
		washingMachine: () => LocalizedString
		/**
		 * 风铃
		 */
		windChimes: () => LocalizedString
		/**
		 * 人群
		 */
		crowd: () => LocalizedString
		/**
		 * 烟花
		 */
		fireworks: () => LocalizedString
		/**
		 * 高速公路
		 */
		highway: () => LocalizedString
		/**
		 * 道路
		 */
		road: () => LocalizedString
		/**
		 * 交通
		 */
		traffic: () => LocalizedString
	}
	categories: {
		/**
		 * 动物
		 */
		animals: () => LocalizedString
		/**
		 * 自然环境
		 */
		nature: () => LocalizedString
		/**
		 * 基础噪音
		 */
		noise: () => LocalizedString
		/**
		 * 场所环境
		 */
		places: () => LocalizedString
		/**
		 * 雨声
		 */
		rain: () => LocalizedString
		/**
		 * 物品声音
		 */
		things: () => LocalizedString
		/**
		 * 交通工具
		 */
		transport: () => LocalizedString
		/**
		 * 城市声音
		 */
		urban: () => LocalizedString
		/**
		 * 合成噪音
		 */
		synthetic: () => LocalizedString
	}
}

export type Formatters = {}
